version: '3.9'
services:
  starrail-relic-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starrail-relic-dev
    # restart: unless-stopped
    volumes:
        - '.:/workspace'
    stdin_open: true
    tty: true
    network_mode: host