name: Github Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: ./scripts/build.sh

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gorobot-demo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}